# Generated by Django 4.2.5 on 2023-12-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('event_type', models.CharField(blank=True, choices=[('wedding', '가족 개인행사'), ('business', '기업 이벤트'), ('public', '사회 단체행사'), ('festival', '기관, 축제등'), ('birthday', '스몰웨딩, 야외결혼'), ('steak', '스테이크 행사'), ('fingerFood', '핑거푸드')], max_length=200, null=True)),
                ('custom_event_type', models.CharField(blank=True, max_length=200, null=True)),
                ('event_place', models.CharField(blank=True, choices=[('실내', '실내'), ('야외', '야외'), ('체육관', '체육관'), ('연회장', '연회장'), ('호텔', '호텔'), ('미정', '미정')], max_length=200, null=True)),
                ('custom_event_place', models.CharField(blank=True, max_length=200, null=True)),
                ('people_count', models.IntegerField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('meal_cost', models.IntegerField(blank=True, null=True)),
                ('custom_tool', models.CharField(blank=True, max_length=200, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('ticket_number', models.IntegerField(blank=True, null=True)),
                ('tool', models.ManyToManyField(blank=True, null=True, to='api.tool')),
            ],
        ),
    ]
