# Generated by Django 4.2.5 on 2023-12-14 22:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('event_type', models.CharField(blank=True, choices=[('wedding', '가족 개인행사'), ('business', '기업 이벤트'), ('public', '사회 단체행사'), ('festival', '기관, 축제등'), ('birthday', '스몰웨딩, 야외결혼'), ('steak', '스테이크 행사'), ('fingerFood', '핑거푸드')], max_length=200, null=True)),
                ('custom_event_type', models.CharField(blank=True, max_length=200, null=True)),
                ('event_place', models.CharField(blank=True, choices=[('실내', '실내'), ('야외', '야외'), ('체육관', '체육관'), ('연회장', '연회장'), ('호텔', '호텔'), ('미정', '미정')], max_length=200, null=True)),
                ('custom_event_place', models.CharField(blank=True, max_length=200, null=True)),
                ('people_count', models.IntegerField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('meal_cost', models.IntegerField(blank=True, null=True)),
                ('tool', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '사각 테이블'), (2, '원탁테이블'), (3, '스텐딩 테이블'), (4, '의자'), (5, '의자커버'), (6, '자바라 텐트 (3m * 6m)'), (7, '몽골텐트 (5m * 5m)'), (8, '단상'), (9, '기본음향'), (10, '무대'), (11, '진행'), (12, '마스터 밴드'), (13, '플래카드'), (14, '필요없는')], max_length=200, null=True)),
                ('custom_tool', models.CharField(blank=True, max_length=200, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('ticket_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
