# Generated by Django 4.2.3 on 2023-07-14 07:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customer_event_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='meal_cost',
            field=models.CharField(blank=True, choices=[('1', '10.000 원'), ('2', '15.000 원'), ('3', '20.000 원'), ('4', '30.000 원'), ('5', '40.000 원'), ('6', '50.000 원'), ('7', '기타')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tool',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '의자'), (2, '테이블'), (3, '텐트'), (4, '음악'), (5, '행사 액세서리'), (6, '기타')], max_length=6, null=True),
        ),
    ]
