# Generated by Django 4.2.3 on 2023-07-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customer_tool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='tool',
        ),
        migrations.AddField(
            model_name='customer',
            name='tool',
            field=models.ManyToManyField(blank=True, to='api.tool'),
        ),
    ]
