# Generated by Django 4.2.3 on 2023-10-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_customer_tool_customer_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tool',
            field=models.ManyToManyField(blank=True, null=True, to='api.tool'),
        ),
    ]
