# Generated by Django 4.2.3 on 2023-10-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_customer_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='event_type',
            field=models.CharField(blank=True, choices=[('가족 개인행사', '가족 개인행사'), ('기업 이벤트', '기업 이벤트'), ('사회 단체행사', '사회 단체행사'), ('기관, 축제등', '기관, 축제등'), ('스몰웨딩, 야외결혼', '스몰웨딩, 야외결혼'), ('스테이크 행사', '스테이크 행사'), ('핑거푸드', '핑거푸드'), ('키타 행사', '키타 행사')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='people_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
