# Generated by Django 4.2.3 on 2023-10-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customer_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='meal_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
