# Generated by Django 4.2.3 on 2023-11-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_customer_meal_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='event_duration',
        ),
        migrations.AddField(
            model_name='customer',
            name='user_note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='event_place',
            field=models.CharField(blank=True, choices=[('실내', '실내'), ('야외', '야외'), ('체육관', '체육관'), ('연회장', '연회장'), ('호텔', '호텔'), ('미정', '미정')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='event_type',
            field=models.CharField(blank=True, choices=[('wedding', '가족 개인행사'), ('business', '기업 이벤트'), ('public', '사회 단체행사'), ('festival', '기관, 축제등'), ('birthday', '스몰웨딩, 야외결혼'), ('steak', '스테이크 행사'), ('fingerFood', '핑거푸드')], max_length=200, null=True),
        ),
    ]
