# Generated by Django 4.2.5 on 2023-11-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_user_note_customer_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custom_tool',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
