# Generated by Django 4.2.5 on 2023-11-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_customer_custom_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custom_event_place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='custom_event_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
