# Generated by Django 4.2.5 on 2023-12-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_customer_custom_event_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='tool',
        ),
        migrations.AddField(
            model_name='customer',
            name='tool',
            field=models.CharField(blank=True, choices=[(1, '사각 테이블'), (2, '원탁테이블'), (3, '스텐딩 테이블'), (4, '의자'), (5, '의자커버'), (6, '자바라 텐트 (3m * 6m)'), (7, '몽골텐트 (5m * 5m)'), (8, '단상'), (9, '기본음향'), (10, '무대'), (11, '진행'), (12, '마스터 밴드'), (13, '플래카드'), (14, '필요없는')], max_length=200, null=True),
        ),
    ]
